#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

[ -d "/metrics" ] && echo "/metrics directory exists so empty it" && rm /metrics/* || echo "/metrics directory does not exist so do nothing"
python3 manage.py migrate
python3 manage.py collectstatic --noinput
gunicorn --preload --worker-class=gevent --worker-connections=$WORKER_CONNECTIONS --workers=$NUM_WORKERS --bind 0.0.0.0:8000 easyerp.wsgi:application
