# Generated by Django 4.0.5 on 2023-03-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=250)),
                ('AccountNumber', models.CharField(max_length=20)),
                ('BalanceType', models.CharField(max_length=20)),
                ('Balance', models.FloatField(default=0)),
            ],
        ),
    ]
