# Generated by Django 4.0.5 on 2023-03-24 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DebitOrCredit', models.CharField(max_length=250)),
                ('Amount', models.FloatField(default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GL.account')),
            ],
        ),
    ]
